### PR TITLE
Hoisting warning on step01

### PR DESCRIPTION
**Pull request by rayfoss**
Especially as it's going out of fashion with let and const

### CODE REVIEW

**Comment by eddyystop** [comment]
Why would we want to have those `hoisted` comments? 

The `//!` and `///` are used by a gitbook plugin to include code from the file into the document. The merging of 2 of them onto one line will break the docs.

**Comment by rayfoss** [comment]
As I was reading the code those to a second to process... "did I miss something or this not defined"

Promise.all seemed pointless... unless you read 3 lines down to see it continues.

**Comment by dehamzah** [comment]
IMHO, I think you don't need to add comment hoisted here too, since in the documentation it clearly says that [our intended audience](https://docs.feathersjs.com/guides/step-by-step/basic-feathers/database-connector.html#we-require-our-dependencies)

> Readers should have reasonable JavaScript experience, ...

And for this,

> As I was reading the code, those to a second to process... "did I miss something or is this not defined"

I think its not going to be like this if we read the [documentation](https://docs.feathersjs.com/guides/step-by-step/basic-feathers/database-connector.html#we-start-an-instance-of-feathers-and-define-its-services) sequentially like i did for example

**Comment by daffl** [comment]
I agree. Thank you for the PR @rayfoss but I think we'll leave this as it is.

**Pull request closed without merging**
