### PR TITLE
Begin Ecosystem section

### PR DESCRIPTION
**Pull request by marshallswain**
Only the official Feathers repos show up in the sidebar under Ecosystem.  I also put a tiny Feathers logo next to each official module/repo in the main Ecosystem page.  We can recategorize the main page later.

screen shot 2016-11-08 at 1 23 21 pm

### CODE REVIEW

**Comment by daffl** [comment]
Should this one go into master? We were going to work from the `auk` branch until the release right?

**Comment by ekryski** [comment]
This probably matters a bit less but any new docs accompanying Auk release stuff go to the Auk branch. Once we are ready to cut over to those docs we:

1. Rebase master into auk
2. create a pre-auk branch of master
3. merge auk into master for any minor updates/fixes
4. start working on the buzzard branch

**Comment by marshallswain** [comment]
Oh yep. I meant it for the auk branch.

**Comment by marshallswain** [comment]
Moved here: https://github.com/feathersjs/feathers-docs/pull/282

**Pull request closed without merging**
