### PR TITLE
Scaling documentation

### PR DESCRIPTION
**Pull request by petermikitsh**
I wrote up the beginnings of some scaling documentation. I cover horizontal scaling via clustering. Eventually it would be ideal to describe how to scale across multiple machines with a load balancer.

### CODE REVIEW

**Comment by petermikitsh** [comment]
A bit of a semantic concern, but arguably I might consider clustering to be a vertical scaling strategy.

It's typically only applied when you're increasing RAM, # of cores ... things typically associated with vertical scale.

However, since configuring clustering is merely increasing the number of processes powering your service, it's technically more of a horizontal strategy.

But beyond this largely academics concern, I feel good about this PR.

**Comment by daffl** [comment]
Awesome, thank you so much! Glad to see this in, we've been meaning to get to it since forever.

**Comment by daffl** [comment]
Please remind me to look into why the build isn't deploying if it doesn't show up on the docs homepage in a bit (I want to tweet out the link).

**Comment by petermikitsh** [comment]
@daffl Just checked, I'm not seeing these changes on docs.feathersjs.com -- it looks like there might be a deployment issue.

**Comment by daffl** [comment]
It's showing up now. No idea what's been going on with GitBook.

**Pull request merged**
