### PR TITLE
feathers.hooks(), not simply hooks()

### PR DESCRIPTION
**Pull request by shawnlauzon**

### CODE REVIEW

**Comment by marshallswain** [comment]
Thanks @shawnlauzon.  I think in order for that to work we need to change the import of `feathers` to `feathers-client`.  Either that or `import hooks from feathers-hooks` and leave the variable as hooks.

**Comment by daffl** [comment]
Thank you @shawnlauzon. I agree with @marshallswain I think that code sample is simply missing a

```
const hooks = require('feathers-hooks');
```

at the top instead. Would you mind updating your PR accordingly?

**Comment by shawnlauzon** [comment]
Thank you, you're right of course. I'll update.

**Comment by shawnlauzon** [comment]
Ok, fixed as well as some other minor changes. My code now works, thanks :)

**Comment by daffl** [comment]
Thank you!

**Pull request merged**
