### PR TITLE
Fixing old or broken links

### PR DESCRIPTION
**Pull request by teddy-error**
Removed redundant directory path (guides/guides) to fix link. Thankfully, at present, it only doesn't work rather than directing to 404 though I'm surprised Gitbook parsing didn't throw error. I imagine it assumes you're linking externally to some other md file which is hilariously unlikely if you ask me x)

### CODE REVIEW

**Comment by teddy-error** [comment]
I ran a scrape of the entire book and this appears to be the only instance of pathing errors resulting in a broken .md link. The other two are valid references to `feathers` Github pages (migrating.md && 1.0 features.md)

**Comment by eddyystop** [comment]
The changes to The Basic guide are OK @daffl.

**Comment by teddy-error** [comment]
Okay. I'm all done for now. 

Worth noting that ba3ea49 needs someone who understands the context of shared authentication better than I to insert a useful link there. From what I could tell, that is either moved into permissions or deprecated- but not sure enough.

**Comment by teddy-error** [comment]
Unclear if oAuth{1,2} modules are still generating changelogs or decidedly removing that feature- it is still in the build file as if it is supposed to occur. So links are not removed entirely in 5486796

**Comment by daffl** [comment]
Thank you for doing this @teddy-error! Also good catch on the changelogs. I added them back and will comment the code back in.

**Pull request merged**
