### PR TITLE
Bug fix: postgres example in step 01

### PR DESCRIPTION
**Pull request by zaheraldefai**
Hi featherjs developers,

I like to support you with your wonderful framework. Here is a small bug fix that avoid a "undefined" and a missing dependencies error message.

Best Regards,
Zaher

### CODE REVIEW

**Comment by eddyystop** [comment]
Thanks! This might have to wait till the 2nd week of June when daffl
returns.

**Comment by daffl** [comment]
It looks fine to me. Didn't you write that example @eddyystop?

**Comment by eddyystop** [comment]
I didn't add that sequelize code into The Basics guide and I'm rather annoyed by it. I'll have to track down how it got there.

**Comment by eddyystop** [comment]
`examples/step/01/db-connector/2.js` and `/3.js` are not referred to in The Basics guide, and they were never tested. They are there in case we want to expand that part of the guide.

So thanks for testing one of them!

**Pull request merged**
