### PR TITLE
Add https://jabpi.com to showcase

### PR DESCRIPTION
**Pull request by thosakwe**
This is a project I was hired to build several months ago, I think it might serve as a nice example of what you can build with Feathers.

### CODE REVIEW

**Comment by ekryski** [comment]
Sweet! Thanks! The filtering is so fast! 😄

**Comment by thosakwe** [comment]
@ekryski Yeah, Feathers and Angular2 are a good combination.

**Comment by daffl** [comment]
Do you think you can help us with an Angular 2 chat guide?

**Comment by thosakwe** [comment]
Sure, when I have time.

**Pull request merged**
