### PR TITLE
Promoting the use of the CLI

### PR DESCRIPTION
**Pull request by derek-watson**

### CODE REVIEW

**Comment by marshallswain** [comment]
Looks good.  Let's make it happen.

**Comment by marshallswain** [comment]
I've been through the guide with this and it worked great.  This is the only issue I identified, which isn't a biggie: https://github.com/feathersjs/feathers-docs/issues/108

**Comment by daffl** [comment]
I'd also like to get it in as soon as possible but maybe we can chat some more tomorrow to figure out what we want to do for releasing this. I'd mainly like to make sure that the CLI gets the attention it deserves e.g. with a separate release post on the blog vs. just quietly merging it into the docs.

**Comment by ekryski** [comment]
I think we can :shipit:. We can do a quick announcement in slack and then I'll do a recap post within the next week or two on Medium that talks about all the new stuff.

**Pull request merged**
