### PR TITLE
update Angular 2 docs

### PR DESCRIPTION
**Pull request by Hongbo-Miao**
- update to latest Angular 2 using `@NgModule`
- add typings for superagent
- follow Angular 2 style guide

### CODE REVIEW

**Comment by Hongbo-Miao** [comment]
wait a sec

**Comment by Hongbo-Miao** [comment]
Based on https://berndsgn.ch/angular2-and-feathersjs/, now I am clear, you still need write your own `Service` and then extend.

**Comment by harangue** [comment]
This is totally fine to be pulled in as-is, but there are just a couple of places that it could be improved (more notes to myself than anything):

1. The changes to use Angular modules are good, but they probably deserve further explanation - the whole providers description isn't quite right.
2. `extends Service` should go away
3. I think the underscore in `_xService` still belongs there - prefixing private vars with underscores is a common pattern.

Thanks for submitting this!

**Comment by Hongbo-Miao** [comment]
I would agree `extends Service` go away.

For underscore, it is just Angular 2 style guide, https://angular.io/styleguide#!#03-04

**Comment by ekryski** [comment]
@harangue if you think it's good I'll let you own this. Let me make sure you have the correct credentials but you can merge this whenever you think it's good enough.

**Comment by apmis** [comment]
Would be nice to extend the guide and show how real time occurs. The guide currently justshows doing rest over sockets. the big draw for feathers is having "real time out of the box".

**Comment by daffl** [comment]
Sadly nobody on the team is using Angular 2 and @harangue who's been doing great work on this before is pretty busy. We can definitely weigh in on the Feathers part but it'll have to be up to someone who knows Angular 2 to get this updated to building the chat guide.

**Comment by daffl** [comment]
I am going to close all Angular guide related PRs since we don't have anybody who can review them.

We are still looking for anybody interested in helping with a chat guide blog post for Angular 2 (and so far since this issue got opened have not had any luck with it).

**Comment by apmis** [comment]
Hi,

We have progressed with doing angular 2 and feathers.

I would discuss with me team and would help close whatever issues are outstanding 

Thanks 

 

Warmest regards

 

Dr Simpa Dania

*Chief Executive Officer/Lead Consultant, Health Informatics, 

Sabaoth Technologies ltd. 

+2348036648712

linkedin:ng.linkedin.com/in/simpadania

skype: simpadania

twitter:@simpadania

**Comment by daffl** [comment]
@apmis That would be great. Can you contact me in [Slack](http://slack.feathersjs.com/) or open an issue here to discuss further?

**Comment by apmis** [comment]
reaching out to you on slack

**Pull request closed without merging**
