### PR TITLE
Publish to Surge.sh with TravisCI

### PR DESCRIPTION
**Pull request by marshallswain**

### CODE REVIEW

**Comment by daffl** [comment]
Cool. I know we still have to get it passing but other question: Does this also build the eBook and PDF versions? If not would it be hard to add those as well?

**Comment by marshallswain** [comment]
I haven't looked, yet, but I doubt it is hard.  For now the Gitbook CI is hopefully producing a real PDF and not a blank one.

**Comment by marshallswain** [comment]
It's working, so we at least have that in the meanwhile.

**Comment by marshallswain** [comment]
Cool.  Node 6.5 to the rescue!

**Pull request merged**
