### PR TITLE
Addition of test/readme.md

### PR DESCRIPTION
**Pull request by jayzamazing**
Added test/readme.md containing a tutorial on how to test using Mocha/Chai and deal with authentication.

### CODE REVIEW

**Comment by jayzamazing** [comment]
PR from demos https://github.com/feathersjs/feathers-demos/pull/16.

**Comment by ekryski** [comment]
Awesome dude! Thanks!

**Comment by daffl** [comment]
@ekryski I think we still need to add it to the summary so that it shows up in the menu.

**Comment by ekryski** [comment]
Already done son! 😄

**Pull request merged**
