### PR TITLE
Minor change in Angular2 documentation

### PR DESCRIPTION
**Pull request by emin93**
Now using feathers-client npm module since this one has everything included with type definitions for FeathersApp and FeathersService

### CODE REVIEW

**Comment by daffl** [comment]
Thank you but I don't think this is correct. The code does use the separate client modules (e.g. https://github.com/feathersjs/feathers-docs/pull/383/files#diff-19f9973ab295886e5b3db9ab4d1c19f8R25) not the different bundled feathers-client module.

**Comment by emin93** [comment]
At first i tried it with the documented modules, but those didn't have any typescript definition files. So i started researching and stumbled upon this module bundle, which seemed to contain all needed modules including type definitions. Correct me if i'm wrong.

With just feathers-client in the package.json, the following modules got installed:
bildschirmfoto 2017-02-15 um 08 40 38

**Comment by emin93** [comment]
In the Angular2 doc you recommend to install the module "feathers", which also contains non-client related files. Imho this is not the expected behavior. When installing "feathers-client", you only get client related files and that is correct.

**Comment by daffl** [comment]
Thank you again for the PR. I am going to close all Angular guide related PRs since we don't have anybody who can review them and we are about to remove frontend framework guides from the documentation and move them into blog posts.

We are still looking for anybody interested in helping with a chat guide blog post for Angular 2.

**Pull request closed without merging**
