### PR TITLE
Update showcase.md

### PR DESCRIPTION
**Pull request by kulakowka**
Add table and shields for plugins list

### CODE REVIEW

**Comment by ekryski** [comment]
I like this. @kulakowka can you re-issue this PR to the `auk` branch? We're hoping to get the new docs out in the week or so.

**Comment by kulakowka** [comment]
@ekryski yes. i can do it. it here? https://github.com/feathersjs/feathers-docs/tree/auk/ecosystem

**Comment by ekryski** [comment]
@kulakowka yup! That same table structure in each section will look great. Just make sure to keep the Feathers icon around to denote core maintained modules. 🍻

**Comment by kulakowka** [comment]
@ekryski cool! I do it tonight!

**Comment by daffl** [comment]
I really like this but it has unfortunately gone a little stale. I'm going to close this PR but it would be great to see this for the [new Ecosystem page](https://docs.feathersjs.com/ecosystem/readme.html).

**Pull request closed without merging**
