### PR TITLE
Added MostlyJS section and modules

### PR DESCRIPTION
**Pull request by NetOperatorWibby**

### CODE REVIEW

**Comment by marshallswain** [comment]
Thanks!

**Comment by eddyystop** [comment]
Maybe this section should be more generatically called `microservices` ?

**Comment by NetOperatorWibby** [comment]
That's what I was going to name it but I saw `DoneJS` so I went with `MostlyJS`. Anything y'all decide is fine with me though!

**Comment by eddyystop** [comment]
I think microservices is more descriptive and other things may end up in
that catgeory. We can look at DoneJS separately.

**Comment by marshallswain** [comment]
yeah.  We're giving client frameworks with more than one entry their own sections.  We tend to generalize on the server packages.

**Comment by marshallswain** [comment]
I've moved it to a Microservices section here: https://github.com/feathersjs/feathers-docs/commit/089a436efedd630a038f4a13c7cd647732113298

Eventually we'll have a guide on how to do this with just Feathers and include realtime.  When that time arrives we can link it from here.

**Pull request merged**
