### PR TITLE
daa feathers-solr adapter reference for query $search

### PR DESCRIPTION
**Pull request by sajov**

### CODE REVIEW

**Comment by daffl** [comment]
This has been added already in the [database section](https://docs.feathersjs.com/ecosystem/readme.html#database).

**Comment by sajov** [comment]
I thought this should introduce the new $seach param and which adapter Support this.

**Comment by sajov** [comment]
I thought this should introduce the new $seach param and which adapter Support this.
Are any plans for further params like $group, $aggregate, $stats, $sum .... ?

**Comment by daffl** [comment]
Oh, got it.

**Pull request merged**
