### PR TITLE
[WIP] Auk reorg - Adding Auth docs

### PR DESCRIPTION
**Pull request by ekryski**

### CODE REVIEW

**Comment by ekryski** [comment]
## DO NOT MERGE YET

Not quite finished but wanted to open it up for visibility.

**Comment by bertho-zero** [comment]
You can put all strategies in a strategies folder for more clarity, no?

**Comment by ekryski** [comment]
@bertho-zero We're trying to keep them only 2 levels deep in the nav, as the 3rd level is for links inside the page.

**Comment by marshallswain** [comment]
@ekryski I'm going to go ahead and merge this so we can iterate on top of it.

**Pull request merged**
