### PR TITLE
Fixed broken link to examples

### PR DESCRIPTION
**Pull request by teddy-error**
Case-sensitive typo

### CODE REVIEW

**Comment by teddy-error** [comment]
I'll submit a consolidated PR with all of the broken links

**Comment by eddyystop** [comment]
Oops, one to many global edits to fix a spelling mistake.

**Comment by teddy-error** [comment]
@eddyystop ?

**Comment by eddyystop** [comment]
Sorry I wasn't clear. That's how  my typo occurred.

**Pull request closed without merging**
