### PR TITLE
Get feathers-hooks-common doc showing in GitBook TOC.

### PR DESCRIPTION
**Pull request by eddyystop**
Cut hooks/common.md in half to see if the original
was too large for GitBook.

### CODE REVIEW

**Comment by ekryski** [comment]
:shipit:

**Comment by ekryski** [comment]
Actually @eddyystop it looks like you need to add them to the `SUMMARY.md` file. So either call this file the same thing `hooks/bundled.md` or update the SUMMARY.md file to have `* [Built-in hooks](hooks/bundled-complete.md)`

**Comment by eddyystop** [comment]
@ekryski  I was trying to see if the original common_hooks.md was too large. So I had SUMMARY.md pointing to a smaller version.

DO NOT MERGE THIS PR. @ekryski may have fixed the problem we were having with GitBook. I'll delete PR once we see the problem is gone.

**Comment by daffl** [comment]
I hope it's ok if I close this one. GitBook still seems to be broken but it'll hopefully just rebuild once we fix it.

**Pull request closed without merging**
